# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hugo Häggmark
title_separator: "|"
masthead_title: "Sagas from the software trenches in the continuing battle between quality, price and time…"
email: hugo.haggmark+webcontact@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sagas from the software trenches in the continuing battle between quality, price and time…
repository: "hugohaggmark/hugohaggmark.github.io"
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Hugo Häggmark"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "ʜᴜꜱʙᴀɴᴅ 🤵👰 ꜰᴀᴛʜᴇʀ ᴏꜰ ᴛʜʀᴇᴇ 👧🧑🧑 ꜱɴᴏʀᴋᴇʟᴇʀ 🤿 ꜱɴᴏᴡʙᴏᴀʀᴅᴇʀ 🏂🏿 ᴅᴇᴍᴏᴄʀᴀᴛɪᴢɪɴɢ ᴍᴇᴛʀɪᴄꜱ 📈"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.hugohaggmark.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hugohaggmark"
    - label: "Contact"
      icon: "fas fa-fw fa-at"
      url: "https://www.hugohaggmark.com/contact/"
    - label: "Experience"
      icon: "fas fa-fw fa-list"
      url: "https://www.hugohaggmark.com/experience/"
    - label: "Projects"
      icon: "fas fa-fw fa-flask"
      url: "https://www.hugohaggmark.com/projects/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hugohaggmark"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "giscus"
  giscus:
    repo_id: "MDEwOlJlcG9zaXRvcnkyNDMyMDAzNjg="
    category_name: "Post Comments"
    category_id: "DIC_kwDODn7xcM4CAiSi"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "dark_dimmed"
    crossorigin: "anonymous"

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-18780240-3"
    anonymize_ip: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
